### ISSUE TITLE
Migrate to PostgreSQL 9.4 

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ideas-and-roadmap#117]
PostgreSQL 9.4 was [just released December 18](http://www.postgresql.org/about/news/1557/), and it has a lot of new features that CKAN can leverage:
- JSONB datatype - now we can have our relational and document databases and eat it too! :) See #82 
- [CKAN Multisite](https://github.com/opendata/CKAN-Multisite)-related features?  Logical Decoding - an API for replication; and Alter System - ability to change cluster-wide server settings without changing postgresql.conf. cc @waldoj  
- Performance, performance, performance
- [Concurrently updatable materialized views](https://wiki.postgresql.org/wiki/What%27s_new_in_PostgreSQL_9.4#REFRESH_MATERIALIZED_VIEW_CONCURRENTLY) - this can be used for #28 and #60

**Comment by davidread** [comment]
Note: Postgresql 8.4 is EOL now, so no-one has any excuse to use it now, and 9.0 is EOL too this summer. See: http://www.postgresql.org/support/versioning/

I think it is clear we should move to a minimum of 9.3 or 9.4.

**Comment by davidread** [comment]
Devs decision - specify 9.2 now as minimum. Remove v8 logic in datastore.

**Comment by davidread** [comment]
Closing, as we've got a minimum of postgres 9.3 now and compatibility with postgres 10 for next release, so I think that satisfies the intention here.
