### ISSUE TITLE
CKANCON 2015, May 27, Ottawa, Canada

### ISSUE THREAD

**Issue by wardi** [ckan/ideas-and-roadmap#120]
I would love to attend an informal gathering focused on CKAN this year. Perhaps before/after [Europython](http://www.europython-society.org/post/106049286320/europython-2015-will-be-in-bilbao-spain) If you're interested too leave a comment and let's organize this thing.

**Comment by rossjones** [comment]
+1 - sounds like a great idea.

**Comment by jqnatividad** [comment]
+100.  Would be nice if CKANcon travels around too.  Perhaps, Europe->Americas->Asia, before/after the local PyCon.  I vote for CKANcon, not CKON :)

**Comment by davidread** [comment]
Count me in!

**Comment by metaodi** [comment]
I'd really like a CKANcon this year :+1:

**Comment by amercader** [comment]
Big +1

**Comment by njall** [comment]
+1 
This would great!

**Comment by umlwbin** [comment]
That would be great!

**Comment by augusto-herrmann** [comment]
+1
Not sure if I would be able to go abroad, but would love to attend to CKANcon.

**Comment by bellisk** [comment]
+1 Would love to attend a CKANcon this year, and adjacent to EuroPython seems like a good time and place.

(Of course, next year it should be in CKANcún, Mexico. :smile:)

**Comment by gjlawran** [comment]
Actually Ottawa is  Hosting the 3rd International Open Data Conference (
http://opendatacon.org/) and Montreal is hosting PyCon  ( (
https://us.pycon.org/2015/)  . These conferences are only 200km and 8 days
apart.

Would be a  good time to learn more about Canada. [?]

**Comment by wardi** [comment]
One's in April and the other is in May. But I'd love to do a CKAN sprint at us.pycon in Montreal if people are interested.

**Comment by davidread** [comment]
I'd come to Montreal w/c 10 April if there was sufficient interest from others.

**Comment by umlwbin** [comment]
I have no budget to travel even within Canada right now, but would love to skype or otherwise remote in if it is possible at some point

**Comment by mattfullerton** [comment]
+1, also for the distributed/Skype variant

**Comment by Aaron-M** [comment]
+1, initially Skype version would be good for us, but overall like the concept. Also be good if was able to be viewed offline rather than live due to time zone differences.

**Comment by jqnatividad** [comment]
Anybody going to Ottawa?  I saw OKFN is one of the conference partners.  Maybe we can have a mini-CKANcon on Saturday, the 30th?
I'm particularly interested in:

  * fostering open data standards using ckanext-scheming, and actually working on deployable schemas aligned to existing standards (housefacts, LIVES, permitdata, etc.), and perhaps, creating a schema registry ala extensions.ckan.org
  * theming
  * spatial-optimized CKAN
  * CKAN Multisite

**Comment by wardi** [comment]
@jqnatividad I'll be there for sure.

**Comment by wardi** [comment]
Should this be part of the IODC unconference http://opendatacon.org/unconference/ ?

**Comment by jqnatividad** [comment]
Great idea! In that way, we don't need to worry about venue and logistics.  Count me in!  Perhaps we should start something more formal than a GH issue - an eventbrite perhaps?

**Comment by rgrp** [comment]
On Steering Group call today Ashley Casovan suggested either the the 27th (day before) or the Saturday (the day after).

**Comment by wardi** [comment]
@rgrp I thought the unconference was 26-27 and so we could do it there, but the page just says 26th now, so maybe that doesn't work after all

**Comment by rgrp** [comment]
@wardi ashley says there is a day in between and can probably locate space

**Comment by Acasovan** [comment]
Hey everyone. Does the 27th work for everyone? I'm getting space and will sort out logistics. @wardi let's meet next week to discuss!

**Comment by wardi** [comment]
@Acasovan sounds good!

https://github.com/ckan/ideas-and-roadmap/issues/120#issuecomment-78523347 is a great start on ideas for sessions. Anyone else have ideas? What would you like to see presented or discussed?

**Comment by davidread** [comment]
27th May sounds good

**Comment by wardi** [comment]
Suggestions from the dev call today:

- arrange a hangout or video conference for those that can't attend in person (including most of the ckan dev team)
- presentations in the morning
  - ckan high level overview for those not already deep in ckan work
  - introduction to CKAN code changes this year
  - short presentations on specific extensions or work being done
  - ckan developer Q+A
- unconference in the afternoon (may be difficult to include in hangount/video conference)

**Comment by umlwbin** [comment]
I love the videoconferencing idea

Sent from Claire's iPad

On Apr 14, 2015, at 07:32, Ian Ward <notifications@github.com<mailto:notifications@github.com>> wrote:


Suggestions from the dev call today:

  *   arrange a hangout or video conference for those that can't attend in person (including most of the ckan dev team)
  *   presentations in the morning
     *   ckan high level overview for those not already deep in ckan work
     *   introduction to CKAN code changes this year
     *   short presentations on specific extensions or work being done
     *   ckan developer Q+A
  *   unconference in the afternoon (may be difficult to include in hangount/video conference)

**Comment by Stephen-Gates** [comment]
Recorded video conference please to help those in wildly different time zones.

**Comment by Starl3n** [comment]
It's on!  Please promote via your networks folks!  

Twitter: #ckancon  + #opendata + #WeAreCKAN +anything else :)

Registration:
http://www.eventbrite.com/e/ckancon-2015-tickets-16681567016?aff=es2

**Comment by jqnatividad** [comment]
Now that CKANcon 2015 is over, is there an archive site where we'll store all the presentations, hackpad, recordings, pictures, etc?

**Comment by wardi** [comment]
Yes! we're working on a blog bost that will include summaries, the video and links to all the presentations

**Comment by TkTech** [comment]
@wardi We can probably close this.

**Comment by wardi** [comment]
Here we go again #177
