### ISSUE TITLE
oEmbed support

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ideas-and-roadmap#125]
[oEmbed](http://oembed.com/) will enable easy embedding of CKAN resources on third party sites like [discourse.org](https://meta.discourse.org/t/what-is-a-onebox/4546) (see #44 ) and it allows data consumers to engage with the data portal beyond just downloading data - e.g. on news sites, blogs, etc.

**Comment by jqnatividad** [comment]
It turns out this is not needed.  The latest discourse actually parses opengraph metadata already.
e.g.
https://talk.beta.nyc/t/mapping-the-bacteria-in-new-york-s-subways/170/5

**Comment by alantygel** [comment]
Hi @jqnatividad ,

It is great that discourse does it, but how about all other applications that rely on oembed protocol to show a preview? Wouldn't it be nice to show a dataset or resource preview in Wordpress, for example?
