### ISSUE TITLE
Apply to Google Summer of Code 2015 to implement some of these idears

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ideas-and-roadmap#127]
GSOC just started accepting applications today - 
https://www.google-melange.com/gsoc/homepage/google/gsoc2015

A tad meta, but this would be a good way to get some ideas off the backlog, whilst training future CKAN contributors :)

**Comment by joetsoi** [comment]
deadline is on the 20th, if we want to do it we'd want a list of ideas with some breif summary collected somewhere. We can take a bunch from the tickets here and convert them into a wiki page either here or on the main ckan repo.

**Comment by joetsoi** [comment]
I made a wiki page on the ckan repo and collected together a few ideas that I thought would be good for students here https://github.com/ckan/ckan/wiki/Google-Summer-of-Code

**Comment by jqnatividad** [comment]
Added Sysadmin/Publisher dashboard idea to the Wiki page.  With the deadline imminent, who's going to file the application?  Who's willing to serve as mentors?  @joetsoi, can you serve as a mentor?

**Comment by joetsoi** [comment]
unlikely, we'd be hard pressed to find any of the devs who can commit the time to do it, especially seeing how late we've left it, but it's still good to keep the ball rolling, last time we were terrible at coming up with a list of idea proposals.

**Comment by jqnatividad** [comment]
Agreed.  Let's keep the ball rolling.  There's still the matter of who's going to file the proposal though. 
IMHO, I think its worth it.  I know from the Semantic Mediawiki side that GSOC has been very productive and resulted in mentees eventually becoming core contributors.

**Comment by jqnatividad** [comment]
GSOC application deadline has passed. Next year perhaps?

**Comment by ulgens** [comment]
What about this year?

**Comment by davidread** [comment]
Great, are you offering?
