### ISSUE TITLE
MS Office Resource View

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ideas-and-roadmap#139]
There's still a lot of [0-star open data](http://5stardata.info/) :smile: like [Powerpoints](http://view.officeapps.live.com/op/view.aspx?src=http%3a%2f%2fvideo.ch9.ms%2fbuild%2f2011%2fslides%2fTOOL-532T_Sutter.pptx) and [heavily-formatted XLS files](https://view.officeapps.live.com/op/view.aspx?src=http%3A%2F%2Flearn.bankofamerica.com%2Fcontent%2Fexcel%2FWedding_Budget_Planner_Spreadsheet.xlsx) that may need to be published in a data portal, perhaps, as part of a dataset package, to explain the machine-readable resources.

Now that Microsoft has a [publicly-available MS Office Documents Viewer service](http://blogs.office.com/2013/04/10/office-web-viewer-view-office-documents-in-a-browser/), why not create ckanext-msofficeview?

**Comment by rossjones** [comment]
I think the embeddable google docs viewer does this too - but for more filetypes.

**Comment by jqnatividad** [comment]
That's even better @rossjones!

It has quite a list of supported file formats https://support.google.com/drive/answer/2423485?hl=en

And perhaps, we can even integrate some OpenOffice support, which google docs viewer doesn't recognize, by using https://github.com/kogmbh/WebODF and create a general purpose docviewer (see #20)

**Comment by rossjones** [comment]
Closed by https://github.com/rossjones/ckanext-officedocs and https://github.com/rossjones/ckanext-gdoc

**Comment by jqnatividad** [comment]
Hi @rossjones, should we include these in extensions.ckan.org?

**Comment by rossjones** [comment]
@jqnatividad Yes, but I don't think anyone is keeping track of the issues on the extensions repo.
