### ISSUE TITLE
Mac OS X support

### ISSUE THREAD

**Issue by reubano** [ckan/ideas-and-roadmap#148]
Shouldn't need a docker image to install a python program.

**Comment by davidread** [comment]
Sure, it can work - e.g. https://github.com/ckan/ckan/wiki/Installing-CKAN-2.2.1-on-Mac-OS-X-10.10.1 We have limited resources and choose to maintain support and instructions for one platform, and we choose a more common server platform - ubuntu.

If you feel strongly then you'd be welcome to do the work or fund us to maintain an official OSX install, and deal with questions, issues and upgrades to the OS package versions going forward.

**Comment by reubano** [comment]
@davidread can you explain what you mean by "an official OSX install"? I'm happy to write up a wiki page once I get everything working.

**Comment by davidread** [comment]
Sure, an official install is one which is documented, with an ongoing commitment to respond to issues and upgrades and keep it working in future versions of the OS and dependencies.

**Comment by reubano** [comment]
Well, I volunteer to write documentation.

**Comment by davidread** [comment]
Cool - no doubt there will be others who will appreciate you writing a wiki
page with your take on it.
