### ISSUE TITLE
Problems if Licence picklist is updated

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ideas-and-roadmap#153]
The NZ Government has just mandated a shift from using the CC 3.0 NZ ports of CC licenses, to the CC 4.0 International version.  This has made us look into the issue of what happens if we update our license picklist (json file) such that some or all of the picklist options no longer match license choices that have been selected for existing datasets.

We foresaw 2 potential issues:
1) will the existing licence values, including any associated URL continue to work; and
2) what happens if you edit an existing record to change something else (e.g. fix a spelling mistake, add a doi or an additional resource, or link to a related paper...) - does the license get affected?

We have experimented on our test installation by updating the json file with the license drop down choices. The good news is that any existing licenses are retained including the link to the specific license details.  
 
However, as we suspected, if you edit an existing record (which say has license CC-BY-NC 3.0 NZ chosen), then because the existing ‘old’ license choice is (possibly) no longer in the (updated) drop down list it reverts to selecting the first choice in the current license list (which happens to be CC-BY), and so if you edit and change something else and then save the update, **the license will get changed to the license first in alphabetical order on the picklist automatically and without warning**.  Obviously this is bad in that a license could unwittingly get changed to something quite different to that which the user originally chose (with potential legal/financial implications).
 
If the value of your licence picklist choices stays the same, but you update the URL associated with them in the json file (e.g. to point to the newest version of the license conditions), then IF you edit/update a dataset the license type chosen will not be changed, BUT the URL it now points to will get changed.   

This is something for users to at least be aware of, and perhaps for CKAN to consider the implications of and if there is a solution.  No doubt as CKAN gets older, more users will find themselves needing to revise the license options they are offering as some may become outdated...

**Comment by davidread** [comment]
Thanks for this @Aaron-M . I've converted this 'idea' into issues, as that seems more appropriate.

**Comment by Aaron-M** [comment]
Thanks David, I meant to post in issues myself, but got the wrong place by mistake.  Your summarising of the issue is more eloquent than my rambling :-)

This relates to your https://github.com/ckan/ckan/issues/2478 issue too, as we had been using a full specification for our licence choices (as 3.0 NZ versions), but to work around the above issue we've reverted to underspecifying to mitigate against complete change in the type of licence.  Hopefully the problem can be resolved quickly so we can revert to a full specification.
