### ISSUE TITLE
Allow plugins to tell datapusher what should and should not be pushed.

### ISSUE THREAD

**Issue by rossjones** [ckan/ideas-and-roadmap#155]
I have a specific use-case where only resources with a specific extra should be pushed to the datapusher and then datastore.  Rather than sending *everything* to the datapusher service, I want more control over what is pushed from my own theme/plugin.

It would be neat if there was someway to register a callback in my plugin that the datapusher extension would check before doing the actual submission.

**Comment by amercader** [comment]
This sounds very reasonable. Something like an `IDataPusher.can_upload()` method.

This should probably be called [here](https://github.com/ckan/ckan/blob/cd843d6ea7e668907f6c51b9448c1fae368ab53b/ckanext/datapusher/plugin.py#L105), before calling `datapusher_submit`. Note that we don't have any dicts at this point, only the resource id. So we either pass the id to extensions or call `resource_show` / `package_show` and pass the dicts (I prefer the former, and let extensions handle this)

Also an `IDataPusher.after_upload()` method [here](https://github.com/ckan/ckan/blob/cd843d6ea7e668907f6c51b9448c1fae368ab53b/ckanext/datapusher/logic/action.py#L161) would be really useful, for instance to trigger further transformations on data uploaded to the DataStore.

**Comment by rossjones** [comment]
For consistency I'll probably call them before_upload and after_upload, and let the before_upload return False to stop processing.  The bigger problem is what to call the file that contains the plugin, seeing as plugin is already taken!  Naming thing is too hard.

**Comment by amercader** [comment]
The "return False to abort" pattern is not used on our `before_/after_*` methods, which are generally meant to modify the dicts. We do have some `can_*` that return a boolean, like [this one](https://github.com/ckan/ckan/blob/cd843d6ea7e668907f6c51b9448c1fae368ab53b/ckan/plugins/interfaces.py#L244).

We don't need to add a new plugin to the DataPusher, but an interface, so `interfaces.py` would do just fine (like [this one](https://github.com/ckan/ckan/blob/cd843d6ea7e668907f6c51b9448c1fae368ab53b/ckanext/datastore/interfaces.py)).

**Comment by rossjones** [comment]
The checks for can_upload had to be done in the action - if it was done in the resource domain object change handler then it would be missed when calling via the API.
