### ISSUE TITLE
Add a Code of Conduct.

### ISSUE THREAD

**Issue by rossjones** [ckan/ideas-and-roadmap#166]
I think CKAN should probably have a Code of Conduct so that what is expected of people is clearly defined and everyone is aware of what is unacceptable.

To my knowledge we've never *needed* one, and there's no reason for the suggestion other than I think it is long overdue that we clarify what is acceptable behaviour.

**Comment by metaodi** [comment]
Good idea, there are a [lot of good examples](https://github.com/todogroup/opencodeofconduct/blob/gh-pages/README.md) out there.

**Comment by davidread** [comment]
I'd love to see us agree something like this.

**Comment by jqnatividad** [comment]
And here's one from CfA - https://github.com/codeforamerica/codeofconduct

Probably, more for the mailing list and ideas-and-roadmap repo.

**Comment by amercader** [comment]
The Code of Conduct has been adopted, check here for more info: http://ckan.org/2016/01/27/code-of-conduct/

**Comment by pwalsh** [comment]
Great initiative - well done.
