### ISSUE TITLE
CKANCon 2016, October 4, Madrid, Spain

### ISSUE THREAD

**Issue by wardi** [ckan/ideas-and-roadmap#177]
Join us in Madrid, Spain on October 4th, for CKANCon 2016, one of the official International
Open Data Conference Pre-Events.

CKANCon is a day packed with talks and discussions showcasing the
incredible work people are doing with CKAN. This includes topics
ranging from uses and best CKAN practices to  technical services and
new extensions. New and existing CKAN users are encouraged to attend.
Full details, including speakers and breakout sessions, will be announced soon.

If you're interested in showcasing your CKAN work, please email
ckancon@ckan.org! We are looking for speakers to give short talks
in-person about upcoming features, extensions, integrations and anything else CKAN.

**Comment by jqnatividad** [comment]
Looking forward to this!

**Comment by amercader** [comment]
CKANCon happened last 4th October and it was a blast. 

Check here for sessions and speakers details:

http://ckan.org/ckancon-2016/

Recordings of the sessions should eventually come up here:

https://www.youtube.com/channel/UC8cKSDSxKSbOnKliM_MhZmQ/videos

And there will be a blog post about it on the ckan.org blog really soon (cc @starl3n)
