### ISSUE TITLE
Allow customization of robots.txt

### ISSUE THREAD

**Issue by torfsen** [ckan/ideas-and-roadmap#178]
Currently, CKAN's `robots.txt` is [a static file](https://github.com/ckan/ckan/blob/5a92e2c39e7dbc5b14b66ecfbd67327a61cbbf44/ckan/public/robots.txt) and hence can only be changed in CKAN itself. However, sometimes one wants to change `robots.txt` for a specific extension (for example to specify the location of the sitemap generated by [ckanext-sitemap](https://github.com/kata-csc/ckanext-sitemap)) or for a specific installation.

I therefore suggest to dynamically create `robots.txt` from a Jinja2 template.

**Comment by torfsen** [comment]
This has been implemented and merged: ckan/ckan#3164.

**Comment by ThrawnCA** [comment]
This [was reverted](https://github.com/ckan/ckan/commit/8ee21484d3ceb6c0f0d9eb8d239a3a97baf2e5ac) in the move to CKAN 2.9 (https://github.com/ckan/ckan/issues/4801), without a clear explanation of why.
