### ISSUE TITLE
Alternative Data Explorers

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ideas-and-roadmap#190]
Recline.js is the current default, bundled viewer for tabular data currently used by CKAN and DKAN.

Compared to other data portal solutions, its starting to lag behind on features.

On several installations, we've even been asked to disable graph, map and filter tabs because of their limited utility.

The community should consider creating alternative data viewers - https://jspreadsheets.com/

**Comment by wardi** [comment]
We're using https://datatables.net/ internally for our datastore tables. It meets our A11y stantards (unlike recline) and I'd love to build a resource view instead of have it in our internal-only extensions.

**Comment by jqnatividad** [comment]
Any chance those existing internal extensions can be open sourced? :)

**Comment by wardi** [comment]
They are open, they're just tied to our theme plugin and recombinant, not as generic and reusable as they could be:
* https://github.com/open-data/ckanext-canada/blob/master/ckanext/canada/templates/internal/package/wet_datatable.html
* https://github.com/open-data/ckanext-canada/blob/master/ckanext/canada/controller.py#L165

**Comment by jqnatividad** [comment]
Not to mention reclineview uses a proxy - jsonpdataproxy.appspot.com.  Can't imagine the bandwidth charges and the performance hit...

**Comment by wardi** [comment]
@amercader mentioned that the jsondataproxy service is used only for resources not uploaded to the datastore.

**Comment by jqnatividad** [comment]
Almost there!
https://github.com/ckan/ckan/pull/3444

**Comment by jqnatividad** [comment]
Anticipating the merge of this PR https://github.com/ckan/ckan/pull/3444, marking this as done.
