### ISSUE TITLE
Datastore backends

### ISSUE THREAD

**Issue by smotornyuk** [ckan/ideas-and-roadmap#193]
In order to make datastore more extensible and encourage people to make improvements to it instead of creating complete replacements(last sentence of article from #192) i suggest some code changes.

- Create `IDatastoreBackend` that allows to use engines another from PostgreSQL for data persisting and searching
- Move all pg-related code from plugin to separate file, probably inside backend class
- Same changes for actions
- Any place from actions that supposed using of pg should use backend object, set during plugin initialization.

As result, we at least three new entities:
**IDatastoreBackend** - interface with `register_backend` method, which should return a list of supported engines. On initialization one of registered backends will be chosen depending on the schema of `write_url`.

**DatastorePostgresBackend** - inheritor of next class with current implementation of backend. 

**DatastoreBackend** class as a base for future extensions. Actually, all backend specific logic must be used only here and any other parts of datastore(plugin, actions, etc.) should use this driver.
List of methods(not complete yet):
- _advanced_search_enabled_  - defines, whether actions like 'datastore_search_sql' are available
- _legacy_mode_enabled_ - ? not sure, it would be better to handle this internally, as only postgres needs this
- _configure_datastore_ - will be called on configuration stage. As for postgres, will contain all logic from current plugin's `configure` method

- _datastore_validate_, _datastore_delete_, _datastore_search_ - will be called by corresponding datastore hooks. obviously, current content of this methods from plugin will be placed inside DatastorePostgresBackend.

- _create_, _delete_,  upsert_,_ _search_,  _advanced_search_ - will be called by corresponding actions.

- _field_names_ - should return names of all possible fields for resource. Not sure, how it will be handled inside schemalesl engines, but it required at least for datastore dump. As alternative, maybe it would be better to define method that will create dump itself..

In addition, it would be cool to have console command for performing migration from one engine to another - create dump of each resource and reapload it so that datapusher can handle next steps. Or internal methods, that will do it directly - probably much better in order not to touch activity stream, revisions ant etc.

**Comment by amercader** [comment]
I think this approach makes a lot of sense. A few comments

* The new interface (`IDatastoreBackend`) could either just register backends and return one like you suggest (and how the [resource uploaders](https://github.com/ckan/ckan/blob/master/ckan/lib/uploader.py) work) or could actually be the backend class itself. @TkTech followed this approach on the PR for new search backends (https://github.com/ckan/ckan/pull/3118).

* Essentially we need to abstract anything on  `datastore/helpers.py` and more importantly `datastore/db.py` to a base class and move the existing code to the Postgres implementation. The logic layer should remain unchanged (apart from calling the relevant backend of course)

* Validation (of incoming parameters) is an action level thing so in principle it should not be affected by this, ie actions get parameters, they get validated and they get pass to the backend class method.

* I would not add an *advanced_search_mode* flag. What advanced means will depend on every backend. What we have now is a `datastore_search_sql` action which may or may not be relevant to other backends, so I think it makes more sense to let backends not implement this, and then not register the action at all if it's not supported.

From your list this is how the base backend class could look like:

```python
class DataStoreBackend():

    def configure(self, config):
        pass

    def create(self, context, data_dict):
        pass

    def upsert(self, context, data_dict):
        pass

    def delete(self, context, data_dict):
        pass

    def search(self, context, data_dict):
        pass

    def search_sql(self, context, data_dict):
        pass

   # Other potentially required fields
   def resource_exists(self, id):
        pass 

   def resource_fields(self, id):
        pass


```

**Comment by wardi** [comment]
I agree, advanced_search_mode can't describe the difference between backends. We also need to look at specific parameters to calls and how they're affected (e.g. postgres types are exposed in the existing datastore_create api)

I've also got 3 PRs on the go related to adding features to datastore:
* https://github.com/ckan/ckan/pull/3414 Data Dictionary support, implemented as postgresql column comments. This adds an "info" parameter that stores a JSON dict per datastore field. Would be great to have it in any backend that can support it.
* https://github.com/ckan/ckan/pull/3384 CLI dump command based on earlier work that allows dumping different formats. Here we just need to know what fields are present so we can export data in a tabular format.
* https://github.com/ckan/ckan/pull/3428 Implements data transformation and validation using postgresql triggers. In its current form it's certainly postgres-only but there might be similar functionality available in other backends that would be great to offer instead.

**Comment by smotornyuk** [comment]
As for first comment from Adria, I prefer using separate class as it prevent plugin from growing too large.

After Ian's notes we have next changes in DatastoreBackend:

```python
class DataStoreBackend():
    ...
    # #3414
    def info(self, id):
         pass

    # #3384 - resource_fields, as suggested by Adria

    # #3428 - triggers are not so common among backends, so we will have them in rare occasions :(
    def create_trigger_function(self, name, definition, or_replace):
         raise NotImplemented()

    def delete_function(self, name)
       raise NotImplemented()
```

**Comment by amercader** [comment]
> def info(self, id):

Let's call it `resource_info`, and keep `info` for a potential function that returns info about the backend itself

> # #3428 - triggers are not so common among backends, so we will have them in rare occasions :(
    def create_trigger_function(self, name, definition, or_replace):

For the first iteration I would limit the abstracted methods of the backend class to the ones that are 
obviously general enough (the ones mentioned in previous comments). Other more specialised stuff like the triggers could still be part of the Postgres Backend class but not of the common interface that other backends would need to implement, ie it could be called via its own independent actions that use pg only methods and that are disabled when using other backends.

If after some iterations, and when there are more backends implemented, we see they are generic enough we can incorporate it to the abstract interface

**Comment by smotornyuk** [comment]
ok, and last notice. You're right, validation suits for any backend, but in current implementation we have `datastore_delete` and `datastore_search` hooks defined in plugin and they contain pg-specific code. In one hand, placing them inside backend will make plugin's code more clear and we can define these methods in base backend class as functions without side-effect so that new backends have no need in  defining them. and if backend needs to change search or delete logic, it just need to add these methods. But in that case IDatastore and IDatastoreBackend will be mixed:(
As opposite, we can perform check inside plugin.py, that currently used backend is postgres and only then apply this hooks. It much more prominent, but in that case few pg-specific functions must be imported inside plugin.py.
in order to get best from both solutions, i can add `datastore_delete_hook` and `datastore_search_hook` just to postgres backend and call them from plugin just in case pg-backend is used. It will prevent us from additional importing and wouldn't make mess inside interfaces

**Comment by smotornyuk** [comment]
I added few methods to base backend class:

```python

...
  def make_private(self, context, data_dict):
        raise NotImplementedError()

    def make_public(self, context, data_dict):
        raise NotImplementedError()

    # used inside `datastore_search` action
    def resource_id_from_alias(self, alias):
        raise NotImplementedError()

    # used by datapusher
    def get_all_ids(self):
        raise NotImplementedError()


```
