### ISSUE TITLE
Materialized Views (Stored Queries) Extension

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ideas-and-roadmap#200]
With all the recent datastore improvements (triggers, performance, data dictionary, etc), perhaps we should revisit implementing this as an extension - see https://github.com/ckan/ideas-and-roadmap/issues/60.

And these "stored queries", especially if they're created as Postgres materialized views, can be treated as "meta-resources" against which the existing CKAN resource viewers & the Datastore API should work with little/no modification.

This will solve several problems:

- make existing visualization extensions more useful.  The problem with the low usability of the existing viz extensions is that vizzes in general are meant to work against aggregated data, not raw observation-level data
- allow us to do joins across related packages/resources
- and make it all performant as the queries are "materialized"
- maybe even use "data dictionary" user-friendly column names to facilitate joins
- can also be leveraged to support multi-lingual column names (by defining a view and leveraging the Postgres AS clause  e.g. "<english_column_name> as <spanish_column_name>")
- to apply view definition recipes (pivots, lookup against reference tables, etc)

For the initial implementation, I don't think an interactive query-builder is required as this should be an admin/curator function, and not a self-service function.  A text field to paste in the view definition and simple validation of the view definition should be good enough.

Perhaps, it can be self-service in future versions.

cc @wardi @davidread @amercader

**Comment by wardi** [comment]
I'd like to do this as a datastore feature: instead of specifying a file to upload or a URL when creating a resource allow the user to provide a query based on other resources.

We'll have to think about how we'll handle users trying to delete dependent resources. Right now datapusher drops and recreates tables when files are re-loaded.

Then there's the name for the UI. We can't call them "Views"  because that's already taken.

**Comment by jqnatividad** [comment]
That workflow makes sense, introducing a "stored query" concept in addition to file and URL.

As for handling dependencies - for the initial KISS implementation, perhaps just track if a materialized view is valid, and then maybe, giving the option to schedule the refresh, and for more "dynamic/active" views, leveraging datastore triggers to refresh mat views whenever the table dependencies are updated (and maybe leveraging system catalog queries - https://wiki.postgresql.org/wiki/Pg_depend_display)

Apart from figuring dependencies to maintain validity of the mat views, it'd be great if we can expose it as metadata as well so users can find "related" tables.  Apart from showing the view definition (for traceability purposes), maybe we can parse out the object dependencies and link to the package/dataset on the UI.

I know related items were [retired and replaced by ckanext-showcase](https://github.com/ckan/ideas-and-roadmap/issues/64) - perhaps we can reintroduce the concept at the datastore level.

By exposing "related tables" as metadata, the user can even discover datastore table relationships, especially for joins. (Alternatively, we can call it "dependencies" if we don't want to bring back "related" as a concept.)

And I agree that we should call it something else so as not to confuse users - I vote "Stored Queries" with "Materialized Queries" as a second choice.

**Comment by jqnatividad** [comment]
Pinging #135 as well, as I can see Stored Queries being leveraged to apply Query Templates as well - e.g.  one large dataset resource automatically having several derivative materialized views (e.g. Quarterly/Yearly, Slicing data by boundary, etc)

**Comment by wardi** [comment]
in progress, moving to https://github.com/ckan/ckan/issues/3816
