### ISSUE TITLE
Extension Registry

### ISSUE THREAD

**Issue by rgrp** [ckan/ideas-and-roadmap#22]
*Note: this isn't strictly a code feature but I think given its close connection to code and its importance to the ecosytem I'm raising it here*

What: a proper registry for all CKAN extensions.

## Work In Progress

**We now have an initial work in progress in form of a google spreadsheet here:**

[Registry Spreadsheet](https://docs.google.com/a/okfn.org/spreadsheets/d/1izCpljO6Et7zLUKcUlB4BzsMZTurENp56Iqi9kXOtgs/edit#gid=0)

**Please add your extensions to this spreadsheet**

## Why (aka User stories)

As a CKAN User I want to know what extensions exist and their status so that I can find ones I can use and know they are production ready (or not)

As a CKAN Developer I want to publish my extension so that others know it exists and can use it

### Current

Currently wiki is being used https://github.com/ckan/ckan/wiki/List-of-extensions but ...

* Easily gets out of date
* Not integrated with workflow
* No support for automation in future

### Future

To be discussed. Some ideas:

* Store extensions list as CSV or JSON file or even as pages in jekyll site
* Simple webapp (or github pages site) to display

Automated Discovery - nice if we automatically discover new extensions without authors having to go outside their normal workflow:

* Publish extensions on github. You must add a .ckanext file to your repo. We can then automatically discover it (?).
* Support for stuff outside github ... (e.g. explicit adding)

**Comment by jqnatividad** [comment]
Now that http://extensions.ckan.org is live, can we close this?

It needs some tweaking (https://github.com/ckan/extensions.ckan.org/issues), but its up.

**Comment by rgrp** [comment]
FIXED. w00t!
