### ISSUE TITLE
Support Google Dataset Search

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ideas-and-roadmap#220]
Google just announced a new service - Dataset Search!

https://www.blog.google/products/search/making-it-easier-discover-datasets/

As CKAN is the underlying technology behind several large portals, it should be optimized so the datasets are easily discoverable by this service.

This reminds me when [schema.org was first announced back in June 2011](https://webmasters.googleblog.com/2011/06/introducing-schemaorg-search-engines.html), the very week of the Semantic Technology Conference in San Francisco - I was there and it was a very "lively" discussion...

It fundamentally changed web discovery, and hopefully, Dataset Search will do the same for open data.

Pinging related ticket - https://github.com/ckan/ckan/issues/1890

**Comment by metaodi** [comment]
If you are using ckanext-dcat, this is already build-in, see my blog post for more information: https://www.liip.ch/en/blog/make-open-data-discoverable-for-search-engines (also crossposted on the CKAN blog at https://ckan.org/2018/04/30/make-open-data-discoverable-for-search-engines/).

**Comment by metaodi** [comment]
The relevant issue is https://github.com/ckan/ckanext-dcat/issues/75 and the PR https://github.com/ckan/ckanext-dcat/pull/108

**Comment by jqnatividad** [comment]
Awesome @metaodi!  Can it be further optimized so its [defaults aligns with Google's guidelines](https://developers.google.com/search/docs/data-types/dataset)?

**Comment by metaodi** [comment]
@jqnatividad it should already be quite complete, since we already got feedback from @danbri working at Google, and I verified my examples with Google's Structured Data Testing Tool. But if you come across something that we should change, please create an issue on ckanext-dcat.

**Comment by TkTech** [comment]
Fantastic article @metaodi! Do we want to close this as handled-by-extension? ckanext-dcat provides the ideal under Google's guidelines (JSON-LD) and scheming allows passing through form attrs for inline annotations.

For those interested there is an active discussion here on HN https://news.ycombinator.com/item?id=17919297.

**Comment by jqnatividad** [comment]
Closing this as ckanext-dcat provides support already

https://twitter.com/amercader/status/1038006552676974593
