### ISSUE TITLE
[ext] Per dataset issue tracker for users to report and track issues with datasets

### ISSUE THREAD

**Issue by rufuspollock** [ckan/ideas-and-roadmap#4]
Issue tracker per dataset
1. user can report issue with dataset (e.g. broken link, missing out of date metadata)
2. notify correct publisher (owning org)
3. way for org admins to process and tick off / respond to issues?

Possibly, need a way for org admins to specify email address where issues/requests are sent to?

Another potential request: make this issues public so that they can be tracked and closed - like on github?
## Work on this

https://github.com/okfn/ckanext-issues
## Colophon

[Original version (with additional comments) at https://trello.com/c/kx5qqKZY/25-flag-issues-ext-for-users-to-report-problems-with-datasets]

**Comment by rgrp** [comment]
A v1 is now nearly complete.

**Comment by sirex** [comment]
What is the status of ckanext-issues? Is it complete and can be used in production?

**Comment by rufuspollock** [comment]
FIXED. Yes it is usable in production I believe. https://github.com/ckan/ckanext-issues
