### ISSUE TITLE
Celery for background tasks?

### ISSUE THREAD

**Issue by davidread** [ckan/ideas-and-roadmap#66]
CKAN has long had some integration with Celery for performing background tasks. However there have been issues and some people say we should do something else. It would be good to resolve this as we need it for https://github.com/ckan/ckan/issues/1796 among other things.

Celery for:
- it is the most used queue for python. Is default for Django.
- it has lots of features you might want, like robustness, retries.

Celery against:
- past problems with using RabbitMQ as a backend. @kindly and @davidread have seen it occasionally just lock up and not run new tasks on the queue until it is restarted. This appeared to be with the version of RabbitMQ (2.7.1 - that comes with Ubuntu 12.04) and may be fixed in more recent version. In the meantime, kindly switched data.gov to harvest using the Redis backend and has not looked back. davidread wants to switch DGU.
- seems a bit difficult to see what's on the queue, what's going on, control. Maybe we just need to read the docs and learn it properly, although basically it is quite complicated.

Alternatives:
- Pika - amqp library written in python, which might make it easier to use
- RQ (python-rq) - a thin wrapper on Redis to make it work as a queue

Tryggvi suggested these Celery tips: https://denibertovic.com/posts/celery-best-practices/ such as using Flower to monitor Celery nicely.

**Comment by wardi** [comment]
@brew Here's the ticket mentioned at the meeting this morning. As discussed above let's settle on Celery + Redis (non-distributed) as the standard approach for queues in ckan. I'm planning to build in that direction with my docker stuff.

**Comment by rossjones** [comment]
I know this seems like it has already been decided, but having looked deeper at it, http://python-rq.org looks very interesting. It's easy to install and configure, and seems widely used (and suggested by) Heroku and is actively developed (https://github.com/nvie/rq).

**Comment by davidread** [comment]
RQ has a small code-base, which is good, and we don't make use of the Celery features it leaves out: AMQP routing/delivery rules, tasks written in non-python languages. However install, setup of tasks and running tasks seem very similar to Celery (particular the versions newer than the one we're on at DGU), so I can't see much advantage in switching on the face of it. But if you do get a chance to convert archiver across to it and see if it is any simpler in reality, then great!

**Comment by TkTech** [comment]
I use both rq and celery on a variety of projects. Both have their places, and celery is significantly more featured than rq.

For CKANs use case, rq is completely sufficient and easy to integrate. Its code complexity is far below that of celery and debugging it is downright enjoyable compared to celery. Its performance is also excellent (mostly because it tightly binds itself to redis instead of trying to support a wide variety of brokers and result stores).

In the cases where you need tens of thousands of workers across thousands of cores, extremely complex routing and highly scaled queues, I would definitely recommend celery.

For CKAN, where the general usage will likely be periods of heavy bulk loading followed by periodic bulk updates and individual record updates, I would just go with rq and keep it as simple as possible - probably just two queues (queue-default (for all tasks) and queue-ui (for user-triggered events such as reindexing a single dataset)).

**Comment by davidread** [comment]
@TkTech thanks v. much for weighing in on this. It sounds very much like we should give it a shot with rq.

**Comment by wardi** [comment]
@TkTech If I want to schedule jobs like I would with cron, how would I do that with rq? I haven't found a nice way to run the cron daemon in the foreground (for use in docker) and I was hoping there would be a solution for periodic jobs in our queue of choice.

**Comment by TkTech** [comment]
@wardi You would typically do that with cron (in the case of rq) or with [beat](http://celery.readthedocs.org/en/latest/userguide/periodic-tasks.html) (in the case of celery). In both cases, a separate process needs to be run to start the jobs (you can technically run beat inside of a worker, but you would never do this except for local development).

There is also the [rq-scheduler](https://github.com/ui/rq-scheduler) 3rd party project which is stable, popular, and extremely easy to use.

**Comment by deniszgonjanin** [comment]
Good to see rq has a scheduler. It's extremely important to have one for CKAN I think. Cron jobs are too simple, and their configuration lives outside of CKAN source, db, or config, introducing state where state shouldn't be. They have to be set up manually, and they have to be migrated manually as well. Cron really becomes inadequate for anything but the simplest CKAN deployments.

It sounds like we could give rq a shot - it seems like a better alternative, but before it's decided we should address:
- Celery works well enough right now w/ redis as a back-end. Is rq better by enough of a margin to justify the work involved in switching?
- Assuming we don't want to keep celery support as a legacy, switching to rq is a non-backwards compatible change. Extensions will need to be updated. As with the previous point, is this worth the hassle?

**Comment by TkTech** [comment]
Celery is [hardly used at the moment](https://github.com/ckan/ckan/search?utf8=%E2%9C%93&q=celery) and I could find no extension that depends on it. They change should have no API impact.

**Comment by thriuin** [comment]
+1 for rq

**Comment by deniszgonjanin** [comment]
It's used in a few extensions that I know of:
- https://github.com/ckan/ckanext-archiver
- https://github.com/ckan/ckanext-qa
- https://github.com/datacats/ckanext-geopusher

We can migrate those easily anough, but celery is also used in at least a few large CKAN projects of orgs and governments that don't always release their code publicly. Don't assume that this change won't impact anybody, that's a terrible way to build a good open source project.

**Comment by rossjones** [comment]
I agree, perhaps abstracting it out might be best.

But if govs are not releasing their code related to ckan, they are breaching the licence :(

**Comment by thriuin** [comment]
Just for the record (and I know no one said otherwise) Cdn open data does release all of our code to GitHub - unless there is something Ian isn't telling me ;-)

**Comment by deniszgonjanin** [comment]
@rossjones @thriuin that's a good point. We could send out a notice to ckan-dev asking if anybody knows where celery is being used, and to point us to the code. If we don't find (m)any cases, we can move to rq?

**Comment by rossjones** [comment]
We can always implement rq alongside, move the core extensions and let people know then should move before release 2.x.y if they're depending on celery?

**Comment by amercader** [comment]
Came hear to talk about schedulers, I'm glad rq has that covered :)

In terms of deprecating celery I don't think that is a major issue. Celery is not even a requirement for CKAN so if somebody or some extension is using it they will be already taking care of installing it. We can announce deprecation (once rq support is implemented and tested!) and keep the celery code on core for a release (what @rossjones said essentially). Maybe write a short guide about how to migrate jobs from celery to rq if necessary.

**Comment by CarlQLange** [comment]
Just dropping in to ask if there's a definitive doc for using celery with CKAN? All I've been able to find is cobbled together from readmes of a few extensions.

**Comment by torfsen** [comment]
@CarlQLange: There is a [section about background tasks](http://docs.ckan.org/en/latest/maintaining/background-tasks.html) in the CKAN documentation.

**Comment by CarlQLange** [comment]
@torfsen Aha! Thank you so much!

**Comment by rossjones** [comment]
This idea now has a [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=33227756)](https://www.bountysource.com/issues/33227756-provide-support-for-background-tasks?utm_source=33227756&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by torfsen** [comment]
There is now a new PR for this, see ckan/ckan#3165.

**Comment by amercader** [comment]
Background jobs are now merged to master thanks to the brilliant job by @torfsen. Check the docs for more details:

http://docs.ckan.org/en/latest/maintaining/background-tasks.html

**Comment by CarlQLange** [comment]
Wow, that looks fantastic. Great job @torfsen.

**Comment by jqnatividad** [comment]
Hi @amercader, 
I know this issue has been closed, but just wondering if https://github.com/datacats/ckanext-webhooks is still usable given that it uses celery?

Also, the background-tasks doc uses webhooks as the first example of what background tasks are useful for.  Is that a "for example" an aspirational or concrete example :)

**Comment by torfsen** [comment]
@jqnatividad, the old Celery system is deprecated but still available. Hence anything that is working now should continue to work. AFAIK there is currently no time plan for removing the Celery system.

**Comment by amercader** [comment]
@jqnatividad, @torfsen wrote a great section on migrating to the new queue framework and on how to support both systems so it should be really easy to update ckanext-webhooks to support it.

**Comment by torfsen** [comment]
@jqnatividad, the documentation @amercader is talking about is here: [Migrating from CKAN’s previous background job system](http://docs.ckan.org/en/latest/maintaining/background-tasks.html#background-jobs-migration)
