### ISSUE TITLE
Separate docker scripts into ckan-docker

### ISSUE THREAD

**Issue by wardi** [ckan/ideas-and-roadmap#98]
We've [asked](https://github.com/ckan/ckan/pull/1991#issuecomment-60244222) @clementmouchet and he has taken the lead and started [ckan-docker](https://github.com/ckan/ckan-docker).

This is a repository focused on dockerizing all the interesting bits of ckan across a number of releases. We need to figure out the right development process and release schedule for this repository, and figure out who's going to be responsible. I will send invitations for ckan-docker commit access to the people that have contributed docker-related pull requests.

This ticket is an invitation for discussion on how the ckan-docker repository should be managed.

**Comment by filipefigcorreia** [comment]
Is the idea to start building the CKAN images on docker hub (e.g., https://registry.hub.docker.com/u/ckan/ckan/) using the files on (ckan-docker)[https://github.com/ckan/ckan-docker]? I'm trying to decide if it's safe to customize that docker image following the (instructions given by the documentation)[http://docs.ckan.org/en/latest/maintaining/installing/install-using-docker.html#customizing-the-docker-image] or if it's more sensible to create my own dockerfiles from scratch at this point.

**Comment by wardi** [comment]
docker work is back in core again
